all:
  children:
    allservers:
      children:
        datacenters:
          children:
            DC-1:
              hosts:
                ansible-target-1:
                  ansible_host: 3.110.102.26
            DC-2:
              hosts:
                ansible-target-2:
                  ansible_host: 13.126.161.14
          vars:
            ansible_connection: ssh
            ansible_user: ec2-user
