#Encode and Decode the String that you use
- name: Convert string to base 64 using python
  hosts: localhost
  tasks:
  - name: Convert the string to base64
    base64mod: #module name
      name: 'hello'
      type: 'encode' #Argument
      new: true
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}' #result output