# Install Nginx using Ansible
# Start and Enable Nginx
# check status of Nginx
- name: Setup nginx server on myserver list (host group)
  hosts: datacenters
  # become is used to elevate the privages in host machine
  become: True
  vars_files:
    - /home/ec2-user/Variables/vars.yaml
  tasks:
    # below we will be using command module of ansible to execute these commands (y will confirm)
    - name: Install the latest version of nginx
      command: amazon-linux-extras install nginx{{ nginx_ver }}=latest -y
      args:
        creates: /sbin/nginx

    # This time to validate service we use "Service module" from Ansible
    - name: Start nginx service
      service:
        name: nginx
        state: started

    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes

    - name: Get nginx installed version
      command: nginx -v
      register: nginx_version

    - name: fetch version of nginx
      debug:
        msg: "The fetched version of nginx is {{ nginx_version.stderr_lines[0] }}"

    - name: Get status of nginx service
      command: systemctl status nginx

    - name: copy configuration file to target
      copy:
        src: "{{ base_path }}ansible.txt"
        dest: "{{ base_path }}"
